---
services:
    python:
        dns:
            - 8.8.8.8
            - 8.8.4.4
        build: python/.
        networks:
            - pgnc-network
        environment:
            DB_HOST: pgncdb
            DB_PORT: 5432
            DB_NAME: pgnc
            DB_USER: pgnc
            DB_PASSWORD: password
        depends_on:
            pgncdb:
                condition: service_healthy
            solr:
                condition: service_started
    solr-client:
        dns:
            - 8.8.8.8
            - 8.8.4.4
        restart: always
        build: solr-client/.
        networks:
            - pgnc-network
        depends_on:
            solr:
                condition: service_started
            python:
                condition: service_completed_successfully
    solr-data:
        build: solr-data/.
        container_name: solr-data
        networks:
            - pgnc-network
        volumes:
            - solr-data:/var/solr/cores
    solr:
        dns:
            - 8.8.8.8
            - 8.8.4.4
        build: solr/.
        networks:
            - pgnc-network
        ports:
            - "8983:8983"
        volumes:
            - solr-data:/var/solr/cores
        depends_on:
            solr-data:
                condition: service_started
    pgnc-data:
        build: db-data/.
        container_name: db-data
        networks:
            - pgnc-network
        volumes:
            - pgnc-data:/var/lib/postgresql/data
    pgncdb:
        dns:
            - 8.8.8.8
            - 8.8.4.4
        image: docker.io/library/postgres:17.0
        container_name: pgncdb
        restart: always
        networks:
            - pgnc-network
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: pgnc
            POSTGRES_PASSWORD: password
            POSTGRES_DB: pgnc
        volumes:
            - ./db-data:/docker-entrypoint-initdb.d
            - pgnc-data:/var/lib/postgresql/data
        depends_on:
            pgnc-data:
                condition: service_started
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U pgnc"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s
    api:
        dns:
            - 8.8.8.8
            - 8.8.4.4
        restart: always
        build: api/.
        networks:
            - pgnc-network
        ports:
            - "3001:3000"
        depends_on:
            pgncdb:
                condition: service_healthy
    angular:
        restart: always
        dns:
            - 8.8.8.8
            - 8.8.4.4
        build: angular/.
        networks:
            - pgnc-network
        ports:
            - "4000:4000"
        depends_on:
            api:
                condition: service_started
    nginx:
        dns:
            - 8.8.8.8
            - 8.8.4.4
        restart: always
        build: nginx/.
        networks:
            - pgnc-network
        ports:
            - "8080:8080"
        depends_on:
            angular:
                condition: service_started
            solr-client:
                condition: service_started
            api:
                condition: service_started
networks:
    pgnc-network:
        driver: bridge
volumes:
    pgnc-data:
    solr-data:
