---
services:
    solr-data:
        build: solr-data/.
        container_name: solr-data
        networks:
            - pgnc-network
        volumes:
            - solr-data:/var/solr/cores
    solr:
        build: solr/.
        networks:
            - pgnc-network
        ports:
            - "8983:8983"
        volumes:
            - solr-data:/var/solr/cores
        depends_on:
            - solr-data
    pgnc-data:
        build: db-data/.
        container_name: db-data
        networks:
            - pgnc-network
        volumes:
            - pgnc-data:/var/lib/postgresql/data
    pgncdb:
        image: postgres:17.0
        platform: linux/amd64
        restart: always
        hostname: pgncdb
        networks:
            - pgnc-network
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: pgnc
            POSTGRES_PASSWORD: password
            POSTGRES_DB: pgnc
        volumes:
            - ./db-data:/docker-entrypoint-initdb.d
            - pgnc-data:/var/lib/postgresql/data
        depends_on:
            - pgnc-data
    api:
        restart: always
        build: api/.
        networks:
            - pgnc-network
        ports:
            - "3001:3000"
        depends_on:
            - pgncdb
    angular:
        restart: always
        build: angular/.
        networks:
            - pgnc-network
        ports:
            - "4000:4000"
    nginx:
        restart: always
        build: nginx/.
        networks:
            - pgnc-network
        ports:
            - "8080:8080"
        depends_on:
            - angular
networks:
    pgnc-network:
        driver: bridge
volumes:
    pgnc-data:
    solr-data:
