---
services:
  python:
    build: python/.
    networks:
      - pgnc-network
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PGPASSWORD: ${DB_PASSWORD}
      SOLR_USERNAME: ${SOLR_ADMIN_USER}
      SOLR_PASSWORD: ${SOLR_ADMIN_PASSWORD}
      SOLR_HOST: ${SOLR_HOST}
      SOLR_PORT: ${SOLR_PORT}
    restart: "no"
    volumes:
      - ./python/output:/usr/src/app/output
      - ./python/input:/usr/src/app/input
      - ./python/bin:/usr/src/app/bin
      - ./db-data/docker-entrypoint-initdb.d:/usr/src/app/db-data
    depends_on:
      pgncdb:
        condition: service_healthy
      solr:
        condition: service_healthy
  solr-client:
    restart: on-failure
    build: solr-client/.
    networks:
      - pgnc-network
    ports:
      - "${LOCALHOST_SOLR_CLIENT_PORT}:${SOLR_CLIENT_PORT}"
    environment:
      SOLR_HOST: ${SOLR_HOST}
      SOLR_PORT: ${SOLR_PORT}
      SOLR_CORE: ${SOLR_CORE}
      SOLR_CLIENT_PORT: ${SOLR_CLIENT_PORT}
      SOLR_USERNAME: ${SOLR_ADMIN_USER}
      SOLR_PASSWORD: ${SOLR_ADMIN_PASSWORD}
    depends_on:
      solr:
        condition: service_healthy
      python:
        condition: service_completed_successfully
    volumes:
      - ./python/output:/usr/src/app/output
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O /dev/null -q \"http://localhost:${SOLR_CLIENT_PORT}/browse?q=pgnc:2&start=0&rows=1\" || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  solr-data:
    build: solr-data/.
    container_name: solr-data
    restart: "no"
    networks:
      - pgnc-network
    volumes:
      - solr-data:/var/solr/cores
  solr:
    build:
      context: solr/.
      shm_size: 256m
    shm_size: 256m
    networks:
      - pgnc-network
    environment:
      SOLR_PORT: ${SOLR_PORT}
      SOLR_OPTS: "-Dsolr.autoSoftCommit.maxTime=10000"
      SOLR_SECURITY_MANAGER_ENABLED: "false"
      SOLR_ADMIN_USER: ${SOLR_ADMIN_USER}
      SOLR_ADMIN_PASSWORD: ${SOLR_ADMIN_PASSWORD}
    ports:
      - "${LOCALHOST_SOLR_PORT}:${SOLR_PORT}"
    volumes:
      - solr-data:/var/solr/cores
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --output /dev/null --show-error --fail --user ${SOLR_ADMIN_USER}:${SOLR_ADMIN_PASSWORD} http://localhost:${SOLR_PORT}/solr/pgnc/select?q=*:*"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s  # Increased to allow for security initialization
    depends_on:
      - solr-data
  pgnc-data:
    build: db-data/.
    container_name: db-data
    restart: "no"
    networks:
      - pgnc-network
    volumes:
      - pgnc-data:/var/lib/postgresql/data
  pgncdb:
    image: docker.io/library/postgres:17.0
    container_name: pgncdb
    restart: always
    networks:
      - pgnc-network
    ports:
      - "${LOCALHOST_DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db-data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgnc-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB && psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1 FROM init_completion'",
        ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 120s
    depends_on:
      - pgnc-data
  api:
    restart: always
    build: api/.
    networks:
      - pgnc-network
    ports:
      - "${LOCALHOST_API_PORT}:${API_PORT}"
    environment:
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_SYNC: ${DB_SYNC}
      DB_AUTOLOAD_ENTITIES: ${DB_AUTOLOAD_ENTITIES}
      PROFILE_API_KEY: ${PROFILE_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TOKEN_AUDIENCE: ${JWT_TOKEN_AUDIENCE}
      JWT_TOKEN_ISSUER: ${JWT_TOKEN_ISSUER}
      JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL}
      JWT_REFRESH_TOKEN_TTL: ${JWT_REFRESH_TOKEN_TTL}
      MAIL_HOST: ${MAIL_HOST}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      API_PORT: ${API_PORT}
    depends_on:
      pgncdb:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O /dev/null -q http://localhost:$${API_PORT}/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  angular:
    restart: always
    build:
      context: angular/.
      dockerfile: Dockerfile
      args:
        - API_USER=${API_USER}
        - API_PASSWORD=${API_PASSWORD}
    networks:
      - pgnc-network
    ports:
      - "${LOCALHOST_ANGULAR_PORT}:${ANGULAR_PORT}"
    environment:
      ANGULAR_PORT: ${ANGULAR_PORT}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O /dev/null -q http://localhost:$${ANGULAR_PORT} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  certbot:
    build:
      context: certbot/.
      dockerfile: Dockerfile
    container_name: certbot
    profiles: ["ssl"]
    volumes:
      - ./certbot/auth-hook.sh:/auth-hook.sh:ro
      - ./certbot/cleanup-hook.sh:/cleanup-hook.sh:ro
      - ./certbot/gcp-key.json:/gcp-key.json:ro
      - certbot-etc:/etc/letsencrypt/:rw
    environment:
      MY_EMAIL: ${MY_EMAIL}
    command:
      - "certonly"  # Each argument as a separate string
      - "--manual"
      - "--preferred-challenges=dns"
      - "--manual-auth-hook=/auth-hook.sh"
      - "--manual-cleanup-hook=/cleanup-hook.sh"
      - "--email=${MY_EMAIL}"
      - "--agree-tos"
      - "--non-interactive"
      - "-d"
      - "plant.genenames.org"
      - "-d"
      - "pgnc.genenames.org"
  nginx:
    restart: always
    build: nginx/.
    networks:
      - pgnc-network
    ports:
      - "${LOCALHOST_NGINX_PORT}:${NGINX_PORT}"
      - "${LOCALHOST_NGINX_SSL_PORT}:${NGINX_SSL_PORT}"
    environment:
      NGINX_PORT: ${NGINX_PORT}
      NGINX_SSL_PORT: ${NGINX_SSL_PORT}
    volumes:
      - certbot-etc:/etc/letsencrypt:ro
    depends_on:
      angular:
        condition: service_healthy
      solr-client:
        condition: service_healthy
      api:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O /dev/null -q http://0.0.0.0:$${NGINX_PORT}/api/health && wget -O /dev/null -q \"http://0.0.0.0:$${NGINX_PORT}/ses/browse?q=pgnc:2&start=0&rows=1\" && wget -O /dev/null -q http://0.0.0.0:$${NGINX_PORT} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
networks:
  pgnc-network:
    driver: bridge
volumes:
  pgnc-data:
  solr-data:
  certbot-etc:
